controllers:
  main:
    containers:
      main:
        image:
          repository: traefik/whoami
          tag: v1.10.1

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      acme.cert-manager.io/http01-edit-in-place: "true"
      kubernetes.io/ingress.class: "nginx"
    hosts:
    - host: ${host}
      paths:
      - path: /
        pathType: Prefix
        service:
          name: main
    tls:
    - secretName: cert-tls
      hosts:
      - ${host}
